apiVersion: v1
kind: Secret
metadata:
  name: mikrotik-nms-secrets
  namespace: mikrotik-nms
type: Opaque
stringData:
  MIKROTIK_NMS_JWT_SECRET: "CHANGE-ME-to-a-random-secret"
  MIKROTIK_NMS_ENCRYPTION_KEY: ""
  MIKROTIK_NMS_DEFAULT_ROS_PASS: ""
